### ISSUE TITLE
Duplicate frame creation

### ISSUE THREAD

**Issue by cont1nuity** [ViksUI/ViksUI#2]
https://github.com/ViksUI/ViksUI/blob/79889f64de6949db7c235d611d0c3812d6072ee6/ViksUI/Main/Core.lua#L283-L284
https://github.com/ViksUI/ViksUI/blob/79889f64de6949db7c235d611d0c3812d6072ee6/ViksUI/Modules/UnitFrames/lib.lua#L119-L120

As frames are not garbage collected, the second (identical) creation is a waste of resources.

**Comment by ViksUI** [comment]
Yes i see. This section is realy old and under replacement/upgrade.
